name: Sync to Azure Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # ðŸ”‘ histÃ³rico completo

      - name: Push to Azure Repos
        run: |
          git config --global user.email "kadu.unisal1@gmail.com"
          git config --global user.name "caduunisal"

          git remote remove azure || true
          git remote add azure https://caduunisal:${AZURE_PAT}@dev.azure.com/carlosramosti/shellscript/_git/shellscript
          git push azure main --force
        env:
          AZURE_PAT: ${{ secrets.AZURE_PAT }}

      - name: Ensure scripts directory exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.AZURE_VM_USER }}/scripts

      - name: Copy repo scripts to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "*.{sh,py,sql}"
          target: "/home/${{ secrets.AZURE_VM_USER }}/scripts/"
          overwrite: true

      - name: Copy crontab file to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "crontab.prod"
          target: "/home/${{ secrets.AZURE_VM_USER }}/"

      - name: Install crontab on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            if [ -f /home/${{ secrets.AZURE_VM_USER }}/crontab.prod ]; then
              crontab /home/${{ secrets.AZURE_VM_USER }}/crontab.prod
              echo "[INFO] Crontab instalado com sucesso!"
              crontab -l
            else
              echo "[ERROR] Arquivo crontab.prod nÃ£o encontrado."
              exit 1
            fi
